import React from 'react';
import classNames from 'classnames';
import CopyableIcon from './CopyableIcon';

export default class IconSet extends React.Component {
  static defaultProps = {
    icons: [],
  }

  icons = {
    direction: ['step-backward', 'step-forward', 'fast-backward', 'fast-forward', 'shrink', 'arrows-alt', 'down', 'up', 'left', 'right', 'caret-up', 'caret-down', 'caret-left', 'caret-right', 'up-circle', 'down-circle', 'left-circle', 'right-circle', 'up-circle-o', 'down-circle-o', 'right-circle-o', 'left-circle-o', 'double-right', 'double-left', 'verticle-left', 'verticle-right', 'forward', 'backward', 'rollback', 'enter', 'retweet', 'swap', 'swap-left', 'swap-right', 'arrow-up', 'arrow-down', 'arrow-left', 'arrow-right', 'play-circle', 'play-circle-o', 'up-square', 'down-square', 'left-square', 'right-square', 'up-square-o', 'down-square-o', 'left-square-o', 'right-square-o', 'login', 'logout', 'menu-fold', 'menu-unfold'],
    suggestion: ['question', 'question-circle-o', 'question-circle', 'plus', 'plus-circle-o', 'plus-circle', 'pause', 'pause-circle-o', 'pause-circle', 'minus', 'minus-circle-o', 'minus-circle', 'plus-square', 'plus-square-o', 'minus-square', 'minus-square-o', 'info', 'info-circle-o', 'info-circle', 'exclamation', 'exclamation-circle-o', 'exclamation-circle', 'close', 'close-circle', 'close-circle-o', 'close-square', 'close-square-o', 'check', 'check-circle', 'check-circle-o', 'check-square', 'check-square-o', 'clock-circle-o', 'clock-circle'],
    logo: ['android', 'android-o', 'apple', 'apple-o', 'windows', 'windows-o', 'ie', 'chrome', 'github', 'aliwangwang', 'aliwangwang-o', 'dingding', 'dingding-o'],
    other: ['lock', 'unlock', 'area-chart', 'pie-chart', 'bar-chart', 'dot-chart', 'bars', 'book', 'calendar', 'cloud', 'cloud-download', 'code', 'code-o', 'copy', 'credit-card', 'delete', 'desktop', 'download', 'edit', 'ellipsis', 'file', 'file-text', 'file-unknown', 'file-pdf', 'file-excel', 'file-jpg', 'file-ppt', 'file-add', 'folder', 'folder-open', 'folder-add', 'hdd', 'frown', 'frown-o', 'meh', 'meh-o', 'smile', 'smile-o', 'inbox', 'laptop', 'appstore-o', 'appstore', 'line-chart', 'link', 'mail', 'mobile', 'notification', 'paper-clip', 'picture', 'poweroff', 'reload', 'search', 'setting', 'share-alt', 'shopping-cart', 'tablet', 'tag', 'tag-o', 'tags', 'tags-o', 'to-top', 'upload', 'user', 'video-camera', 'home', 'loading', 'loading-3-quarters', 'cloud-upload-o', 'cloud-download-o', 'cloud-upload', 'cloud-o', 'star-o', 'star', 'heart-o', 'heart', 'environment', 'environment-o', 'eye', 'eye-o', 'camera', 'camera-o', 'save', 'team', 'solution', 'phone', 'filter', 'exception', 'export', 'customer-service', 'qrcode', 'scan', 'like', 'like-o', 'dislike', 'dislike-o', 'message', 'pay-circle', 'pay-circle-o', 'calculator', 'pushpin', 'pushpin-o', 'bulb', 'select', 'switcher', 'rocket', 'bell', 'disconnect', 'database', 'compass', 'barcode', 'hourglass', 'key', 'flag', 'layout', 'printer', 'sound', 'usb', 'skin', 'tool', 'sync', 'wifi', 'car', 'schedule', 'user-add', 'user-delete', 'usergroup-add', 'usergroup-delete', 'man', 'woman', 'shop', 'gift', 'idcard', 'medicine-box', 'red-envelope', 'coffee', 'copyright', 'trademark', 'safety', 'wallet', 'bank', 'trophy', 'contacts', 'global', 'shake', 'api'],
    adparlor: [
      'icon-swipe-up-arrow', 'icon-revert-arrow', 'icon-revert', 'icon-cricket', 'icon-platform_google', 'icon-NCAA', 'icon-side-triangle', 'icon-sq_Google', 'icon-sq_Snapchat', 'icon-snapchat', 'icon-dcm', 'icon-hockey', 'icon-weather', 'icon-olympic-rings', 'icon-campaign-data', 'icon-genius', 'icon-engine', 'icon-pencil', 'icon-sq_Instagram', 'icon-platform_instagram', 'icon-shape-diamond', 'icon-shape-circle', 'icon-shape-hexagon', 'icon-shape-square', 'icon-shape-star', 'icon-shape-triangle', 'icon-platform_facebook', 'icon-platform_pinterest', 'icon-platform_tumblr', 'icon-platform_youtube', 'icon-platform_snapchat', 'icon-platform2_instagram', 'icon-platform_twitter', 'icon-platform_yahoo', 'icon-sq_Yahoo', 'icon-copy', 'icon-apLogoSpin', 'icon-sq_Pinterest', 'icon-sq_Tumblr', 'icon-sq_YouTube', 'icon-sq_Facebook', 'icon-sq2_Instagram', 'icon-sq_Twitter', 'icon-tumblr-circle', 'icon-cycle', 'icon-youtube-circle', 'icon-ap', 'icon-cycle-shit', 'icon-ap3', 'icon-magnifying-glass', 'icon-download-file', 'icon-close', 'icon-updates', 'icon-square-checkbox-selected', 'icon-square-checkbox-empty', 'icon-square-checkbox-checked', 'icon-Icon_semi-checked', 'icon-basic-video', 'icon-basic-picture', 'icon-search-app-ranker', 'icon-create-tweet', 'icon-thinner-circle-checked', 'icon-thinner-circle-empty', 'icon-appInstall_engage', 'icon-brandAware_engage', 'icon-ecommerce_dr', 'icon-push-back', 'icon-new-flag', 'icon-beta', 'icon-twitter-upload', 'icon-facebook-upload', 'icon-tw-upload', 'icon-fb-upload', 'icon-split', 'icon-objective', 'icon-targeting', 'icon-campaigns', 'icon-thin-x', 'icon-apply-up',
      'icon-apply-down', 'icon-email-sign', 'icon-twitter-sign', 'icon-skype-sign', 'icon-phone-sign', 'icon-linkedin-sign', 'icon-facebook-sign', 'icon-checkbox-unchecked', 'icon-checkbox-partial3', 'icon-checkbox-partial', 'icon-dotted-check', 'icon-broad', 'icon-specific', 'icon-tw-promoted', 'icon-check-sign3', 'icon-notices', 'icon-bball2', 'icon-bball', 'icon-timer', 'icon-carousel', 'icon-refresh5', 'icon-Measure', 'icon-football2', 'icon-football1', 'icon-number1', 'icon-number2', 'icon-number3', 'icon-number4', 'icon-number5', 'icon-number6', 'icon-number7', 'icon-number8', 'icon-number9', 'icon-number0', 'icon-dark-number1', 'icon-dark-number2', 'icon-number13', 'icon-number14', 'icon-number15', 'icon-number16', 'icon-number17', 'icon-number18', 'icon-number19', 'icon-number20', 'icon-film', 'icon-thermometer2', 'icon-edit', 'icon-profile', 'icon-pin', 'icon-pin2', 'icon-profile2', 'icon-pig', 'icon-rain', 'icon-snow', 'icon-lightning', 'icon-sun', 'icon-moon', 'icon-cloudy', 'icon-cloudy2', 'icon-pop-out', 'icon-pop-in', 'icon-crop', 'icon-envelope-open', 'icon-envelope', 'icon-ruler', 'icon-atom', 'icon-justice', 'icon-file-add', 'icon-file-subtract', 'icon-tools2', 'icon-link2', 'icon-female', 'icon-male', 'icon-stop3', 'icon-target', 'icon-chat', 'icon-megaphone', 'icon-grid2', 'icon-clipboard', 'icon-money', 'icon-open', 'icon-sale', 'icon-beaker', 'icon-unlocked2', 'icon-locked', 'icon-genius-symbol', 'icon-happy', 'icon-sad-face', 'icon-thinner-circle-notice', 'icon-cancel', 'icon-videocamera', 'icon-instagram', 'icon-instagram3', 'icon-chevron-thin-right', 'icon-chevron-thin-left',
      'icon-export', 'icon-mobile2', 'icon-mail', 'icon-pencil3', 'icon-paperclip', 'icon-user2', 'icon-users', 'icon-user-add', 'icon-search', 'icon-thumbs-down', 'icon-thumbs-up', 'icon-cog3', 'icon-thunder', 'icon-bolt', 'icon-dashboard', 'icon-credit-card', 'icon-graph', 'icon-bars2', 'icon-pie2', 'icon-statistics', 'icon-adsizes', 'icon-thermometer', 'icon-cart2', 'icon-earth', 'icon-retweet', 'icon-info', 'icon-erase', 'icon-help', 'icon-warning', 'icon-cards', 'icon-facebook2', 'icon-twitter2', 'icon-code', 'icon-infinity', 'icon-signal', 'icon-chevron-left', 'icon-triangle-right', 'icon-triangle-up', 'icon-triangle-down', 'icon-triangle-left', 'icon-chevron-down', 'icon-chevron-up', 'icon-chevron-right', 'icon-instagram2', 'icon-menu2', 'icon-layout', 'icon-list2', 'icon-list22', 'icon-add-to-list', 'icon-question-sign', 'icon-info-sign', 'icon-external-link', 'icon-publish', 'icon-close-x', 'icon-arrow-left', 'icon-arrow-down', 'icon-arrow-up', 'icon-arrow-right', 'icon-ellipsis', 'icon-save', 'icon-tag-hang', 'icon-quote', 'icon-link', 'icon-linkedin2', 'icon-tools', 'icon-trophy2', 'icon-comment', 'icon-heart2', 'icon-share2', 'icon-browser', 'icon-rss', 'icon-vcard', 'icon-history2', 'icon-exchange', 'icon-paperplane', 'icon-forward2', 'icon-home', 'icon-code3', 'icon-warning2', 'icon-cycle2', 'icon-cw', 'icon-ccw', 'icon-shuffle', 'icon-add-to-list2', 'icon-docs', 'icon-library-lists', 'icon-arrow-right3', 'icon-menu3', 'icon-twitter-circle2', 'icon-facebook-circle3', 'icon-cycle3', 'icon-house', 'icon-images', 'icon-camera', 'icon-video-camera', 'icon-play', 'icon-picture', 'icon-tag',
      'icon-tags', 'icon-file', 'icon-copy4', 'icon-paint-format', 'icon-paste', 'icon-credit', 'icon-phone', 'icon-support', 'icon-folder-open', 'icon-folder-close', 'icon-alarm', 'icon-time', 'icon-history', 'icon-map-marker', 'icon-cart', 'icon-calendar', 'icon-bubbles2', 'icon-bubble', 'icon-reply', 'icon-forward', 'icon-redo', 'icon-undo2', 'icon-quotes-left', 'icon-disk', 'icon-print', 'icon-drawer3', 'icon-user', 'icon-zoom-in', 'icon-zoom-out', 'icon-expand', 'icon-contract', 'icon-key', 'icon-unlocked', 'icon-lock', 'icon-wrench', 'icon-gift', 'icon-bars', 'icon-pie', 'icon-wand', 'icon-gear', 'icon-equalizer', 'icon-trophy', 'icon-list', 'icon-delete', 'icon-heart', 'icon-star', 'icon-star-outline', 'icon-globe', 'icon-cloud-upload', 'icon-download', 'icon-cloud', 'icon-menu', 'icon-flag', 'icon-eye', 'icon-bookmark', 'icon-eye-blocked', 'icon-attachment', 'icon-bookmarks', 'icon-sad', 'icon-sad2', 'icon-smiley', 'icon-smiley2', 'icon-play2', 'icon-pause', 'icon-stop', 'icon-check', 'icon-minus', 'icon-play3', 'icon-pause2', 'icon-stop2', 'icon-arrow-up-left-circle', 'icon-arrow-up2', 'icon-arrow-up-right2', 'icon-arrow-right2', 'icon-arrow-down-right2', 'icon-arrow-left2', 'icon-arrow-down-left2', 'icon-arrow-down2', 'icon-checkbox-checked', 'icon-checkbox-unchecked2', 'icon-radio-checked', 'icon-radio-unchecked', 'icon-checkbox-partial2', 'icon-table', 'icon-table2', 'icon-bold', 'icon-underline', 'icon-italic', 'icon-filter', 'icon-share', 'icon-paragraph-center', 'icon-paragraph-left', 'icon-paragraph-right', 'icon-paragraph-justify', 'icon-twitter', 'icon-android', 'icon-apple', 'icon-linkedin',
      'icon-skype', 'icon-paypal', 'icon-pinterest', 'icon-address-book', 'icon-qrcode', 'icon-alarm2', 'icon-mobile', 'icon-tv', 'icon-spam2', 'icon-facebook-circle', 'icon-twitter-circle', 'icon-file-excel', 'icon-chrome', 'icon-firefox', 'icon-IE', 'icon-safari', 'icon-Celsius', 'icon-Fahrenheit', 'icon-none', 'icon-plus-sign', 'icon-remove', 'icon-fork', 'icon-file-pdf', 'icon-file-word', 'icon-file-zip', 'icon-file-powerpoint', 'icon-file-xml', 'icon-grid', 'icon-calculator', 'icon-windows8', 'icon-denied', 'icon-move', 'icon-move-vertical', 'icon-move-horizontal', 'icon-new-tweet', 'icon-archive', 'icon-loop', 'icon-spinner', 'icon-binoculars', 'icon-briefcase', 'icon-clock', 'icon-map-pin-fill', 'icon-cursor', 'icon-file-pdf2', 'icon-file-excel2', 'icon-file-zip2', 'icon-file-powerpoint2', 'icon-file-xml2', 'icon-file-openoffice', 'icon-file-word2', 'icon-file-notice', 'icon-x', 'icon-facebook', 'icon-building', 'icon-lab', 'icon-certificate', 'icon-gears', 'icon-minus2', 'icon-plus', 'icon-minus-sign', 'icon-laptop', 'icon-screen', 'icon-tablet', 'icon-file-paper', 'icon-bell2', 'icon-quill', 'icon-facebook3', 'icon-eyeball', 'icon-group-arrow', 'icon-uniF7D7', 'icon-uniF6A0', 'icon-uniF4A4', 'icon-thin-circle-empty', 'icon-uniF544', 'icon-uniF551', 'icon-uniF552', 'icon-check-sign', 'icon-uniF47D', 'icon-greenlightbulb', 'icon-blackberry', 'icon-circle-left', 'icon-circle-down', 'icon-circle-up', 'icon-circle-right', 'icon-uniF009', 'icon-uniF014', 'icon-domain2', 'icon-webpage', 'icon-spam', 'icon-codeigniter', 'icon-refresh2', 'icon-push', 'icon-pull', 'icon-spreadsheet', 'icon-upload', 'icon-youtube',
      'icon-full-circle', 'icon-next', 'icon-equalizer2', 'icon-twocolumnright', 'icon-twocolumnright2', 'icon-duplicate', 'icon-ruler2', 'icon-snowflake', 'icon-calculator2', 'icon-basketball', 'icon-settings5', 'icon-info2', 'icon-alert', 'icon-redo2', 'icon-loading2', 'icon-feed', 'icon-bell', 'icon-undo', 'icon-spinner2', 'icon-spinner3', 'icon-spinner4', 'icon-spinner5', 'icon-spinner6', 'icon-refresh', 'icon-play4', 'icon-check-semi', 'icon-check-empty', 'icon-code2', 'icon-check-sign2',
    ],
  };

  render() {
    const { className, catigory } = this.props;
    const listClassName = classNames({
      'anticons-list': true,
      clearfix: true,
      [className]: !!className,
    });
    return (
      <ul className={listClassName}>
        {this.icons[catigory].map(type => <CopyableIcon key={type} type={type} catigory={catigory} />)}
      </ul>
    );
  }
}
